### ISSUE TITLE
Can't install it in fedora silverblue

### ISSUE THREAD

**Issue by sifat06** [sukhmeetbawa/shell-theme-upstream#3]
As fedora silverblue has immutable filesystem, It won't let me edit the /usr directory. Is there any way to ship it as an rpm package?
The error messege: `mv: cannot move '/usr/share/gnome-shell/gnome-shell-theme.gresource' to '/usr/share/gnome-shell/gnome-shell-theme.gresource~': Read-only file system`

**Comment by sukhmeetbawa** [comment]
well you can install it locally now. I don't have much experience with rpm so I will have to look into it

**Comment by sukhmeetbawa** [comment]
is it fixed?

**Comment by sifat06** [comment]
Yes it is! and sorry for late reply.
