### ISSUE TITLE
Dock separator missing

### ISSUE THREAD

**Issue by seanleavy** [sukhmeetbawa/shell-theme-upstream#4]
Hi running the latest version of your script. The dock separator is missing between favourites and the running apps. 

Separator should be between Gedit and Chromium below

![Screenshot from 2022-02-24 22-58-58](https://user-images.githubusercontent.com/2906363/155621794-5e353833-5c6e-4b7c-85a9-ca056bf28e95.png)

I think its been fixed upstream.

Raised here: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4969#note_1376874

Addressed here: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4969#note_1377383

Merge request to fix it: https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2161

Running Fedora 35

Gnome 41.3

**Comment by sukhmeetbawa** [comment]
I will fix it in few days

**Comment by yavko** [comment]
I think this is still happening, I just installed it, and there is no separator, is it because I'm using dash to dock?

**Comment by sukhmeetbawa** [comment]
try now i accidentally pushed changes to main instead of master

**Comment by yavko** [comment]
> try now i accidentally pushed changes to main instead of master

Ok let me try it!

**Comment by yavko** [comment]
It works! After 2 reboots because I forgot to run `git pull` the first time :|

**Comment by sukhmeetbawa** [comment]
Happy to hear.
