### ISSUE TITLE
Gnome 3 support possible?

### ISSUE THREAD

**Issue by seanleavy** [sukhmeetbawa/shell-theme-upstream#6]
Hi, was wondering if Gnome 3.38 support is feasible? I have this Gnome version on my Debian stable machine.

No worries if it can't of course!

Rgds

**Comment by sukhmeetbawa** [comment]
Well I tried it on live iso of debian and it seems to be working. If there is some issue then you can reopen this issue. Closing for now.

**Comment by seanleavy** [comment]
Cool. Thanks for actually taking the time to do that. Appreciated.

Just got back into to town and tried it out on my Debian PC. It installs successfully.

Only issues I've found are:

- The dock & workspace tray missing their backgrounds (see first pic).
- Dock running app indicators
- OSD pop-ups are still the old style

<br>
<br>

## Dock & Workspaces tray:

![Screenshot from 2022-04-29 14-09-28](https://user-images.githubusercontent.com/2906363/165950759-084b8a71-f210-430a-bc7d-22b2672615a0.png)

#### random screengrab from internet showing the background:
![GNOME-Activity-Overview](https://user-images.githubusercontent.com/2906363/165955479-9a61ad0b-7bee-497a-ab59-fe71a9c01641.jpg)


<br>
<br>
<br>
<br>


## OSD:

![Screenshot from 2022-04-29 14-18-45](https://user-images.githubusercontent.com/2906363/165952158-8a12580a-c95b-48f9-9fae-5d064e28b08e.png)

#### Working exmaple of new OSD from internet:
![gnome-42-new-shell-theme-screenshot](https://user-images.githubusercontent.com/2906363/165956206-3998bc58-e5a9-4a08-8e88-63146b2ccf27.jpg)

<br>
<br>
<br>
<br>

## Running app indicator
![Screenshot from 2022-04-29 14-09-28](https://user-images.githubusercontent.com/2906363/165955145-e41de353-59c4-4378-adf6-bb694d3eecf8.png)

<br>
<br>
<br>
<br>


Dunno how easy any of this would be to fix/backport to be honest


Rgds

**Comment by sukhmeetbawa** [comment]
The new OSD design can't be implemented since it require changes to other files as well which you can see in [this commit](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/f88222edd6ff4dd1fcc4b1de9ec5176d9fdbf294), the rest are CSS changes which I don't know much about so can't help with that.
